### ISSUE TITLE
Stack underflow when using `pred`

### ISSUE THREAD

**Issue by sjamaan** [wehu/prcc#1]
`(parse-string "" (pred (eof) (eof)))` gives me an error: `Error: (stack-pop!) stack underflow: #,(stack ())`

The real code is more complicated than that, where `(sel ... (eof))` is involved in the parser. I think this should simply always succeed.

**Comment by sjamaan** [comment]
Actually, what I'm really trying to do is `(parse-string "" (pred (sel (char #\a) (str "")) (eof)))`, but that gives me another error:

```
parsing '' failed:
    (end of stream)@(1, 1)
#f
```

Consuming an empty string should be possible at any point in the string, including at EOF.

**Comment by wehu** [comment]
yeah,  pred and str do not handle well with eof. thanks for report and fixed already just now [14f77109671ddbf35bb38cab1888fa14ff0e6bfd](https://github.com/wehu/prcc/commit/14f77109671ddbf35bb38cab1888fa14ff0e6bfd)
