### ISSUE TITLE
More inconsistent behaviour at eof with `act`

### ISSUE THREAD

**Issue by sjamaan** [wehu/prcc#3]
I would expect this to return 1, because the `char` parser fails, calling the failure continuation which produces 1:

```
(use data-structures prcc)
(parse-string "" (act (char #\x) identity (constantly 1)))
```

However, it gives an error:

```
parsing '' failed:
    (end of stream)@(1, 1)
#f
```

**Comment by wehu** [comment]
act always return #f if parser failed. Just changed to return the value of callback of failure to allow user have a chance to do something.

**Comment by sjamaan** [comment]
Excellent, thanks!

**Comment by sjamaan** [comment]
With this fix, I finally was able to finish my port of `uri-generic` to prcc.  It would be nice if you could tag a release.

About the uri-generic port: As a bit of a hobby, I maintain a whole slew of alternative implementations of the uri-generic egg, using various different parsing libraries. This started because I always found the original uri-generic kind of hard to maintain, what with the `string->list` conversion and pattern matching which it does on those lists. So far, none of the parsing libraries has been able to outperform the matchable implementation, so I'm sticking with matchable for the foreseeable future.  Uri-generic is a well-tuned, fully functional real-world parser, which (very) strictly conforms to RFC3986 and has an extensive test suite, but it is small enough to rewrite in an afternoon. This makes it extremely suitable as a sort of benchmark for evaluating different parser generators.

Have a look at the [code](http://bugs.call-cc.org/browser/project/release/4/uri-generic/trunk/alternatives).  So far, I really like prcc (except for the fact that its error reporting can't be customized), but unfortunately it's not very performant, compared to the other implementations.

Thanks for your quick responses on these issues!

**Comment by wehu** [comment]
Thanks! I tagged a 0.3 release. I will have a look at your code. I know the performance is not good enough. I stopped to improve at some point but now I may need to continue again. :) Thanks again for you like it！
