### ISSUE TITLE
"seq_" confused by EOF

### ISSUE THREAD

**Issue by colossoi** [wehu/prcc#4]
It seems that "seq_" is confused when it is given one sub-parser, followed by (eof), and the input does not have a trailing space.  The following yields a parse failure:

```
(parse-string "asdf" (seq_ (str "asdf") (eof)))
```

These succeed, however:

```
(parse-string "asdf123" (seq_ (str "asdf") (str "123")))
(parse-string "asdf " (seq_ (str "asdf") (eof)))
```

**Comment by wehu** [comment]
Thanks for report @laslowh . By default, seq_, join_ will skip spaces but looks like regexp \s\* does not handle well with eof. I just fixed it.

**Comment by colossoi** [comment]
Thanks!  Nice work on the library.
